name: EDTEAM FastAPI demo

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest test/test.py

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Deploy
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }}
        run: |
          echo "[DEPLOY] Starting deployment of $DOCKER_IMAGE"
          docker pull $DOCKER_IMAGE || { echo "[DEPLOY] ERROR: Failed to pull Docker image" | mail -s "🚨 [DEPLOY FAILED] Docker Pull" luisscasas45@gmail.com; exit 1; }

          API=$(docker ps -q -f name=api)
          if [ ! -z "$API" ]; then
            echo "[DEPLOY] Stopping current container"
            docker stop $API || { echo "[DEPLOY] ERROR: Failed to stop existing container" | mail -s "🚨 [DEPLOY FAILED] Stop Container" luisscasas45@gmail.com; exit 1; }
            docker rm $API || { echo "[DEPLOY] ERROR: Failed to remove existing container" | mail -s "🚨 [DEPLOY FAILED] Remove Container" luisscasas45@gmail.com; exit 1; }
          fi

          echo "[DEPLOY] Starting new container"
          docker run -d --name api -p 80:8080 $DOCKER_IMAGE || { echo "[DEPLOY] ERROR: Failed to start new container" | mail -s "🚨 [DEPLOY FAILED] Start Container" luisscasas45@gmail.com; exit 1; }

      - name: Check service
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: |
          echo "[CHECK] Verifying service health..."
          for i in {1..10}; do
            RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" $ENDPOINT) || RESPONSE=0
            if [ "$RESPONSE" -eq 200 ]; then
              echo "[CHECK] Service is responding!"
              break
            fi
            echo "[CHECK] Waiting for service to respond..."
            sleep 3
          done

          if [ "$RESPONSE" -ne 200 ]; then
            echo "[CHECK] ERROR: Service did not respond after 10 attempts" | mail -s "🚨 [SERVICE UNRESPONSIVE]" luisscasas45@gmail.com
            exit 1
          fi

          echo "[SUCCESS] Deployment and service check completed successfully!" | mail -s "✅ [DEPLOY SUCCESS]" luisscasas45@gmail.com
