name: EDTEAM FastAPI demo

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest test/test.py

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Deploy
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/edteam-fastapi-demo:${{ github.sha }}
        run: |
          echo "[DEPLOY] Downloading new version"
          docker pull $DOCKER_IMAGE || exit 1

          echo "[DEPLOY] Stopping current version"
          sleep 1
          API=$(docker ps -q -f name=api)
          if [ ! -z "$API" ]; then
            docker stop $API
            docker rm $API
          fi

          echo "[DEPLOY] Starting new container"
          docker run -d --name api -p 80:8080 $DOCKER_IMAGE || exit 1

      - name: Checkout service
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: |
          echo "[CHECK] Checking service status..."
          for i in {1..10}; do
            RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" $ENDPOINT) || RESPONSE=0
            if [ "$RESPONSE" -eq 200 ]; then
              echo "[CHECK] Service is up!"
              break
            fi
            echo "[CHECK] Waiting for service..."
            sleep 3
          done

          if [ "$RESPONSE" -ne 200 ]; then
            echo "[CHECK] Service unresponsive after 10 retries"
            exit 1
          fi

          echo "[SUCCESS] Service check completed"

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ job.status == 'success' && '✅ Deployment Successful' || '🚨 Deployment Failed' }}
          body: ${{ job.status == 'success' && 'El deploy y la verificación del servicio se completaron correctamente.' || 'Hubo un problema durante el deploy o el chequeo del servicio.' }}
          to: luisscasas45@gmail.com
          from: ${{ secrets.SMTP_USERNAME }}
